[package]
name = "argon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
indoc = "2"
indexmap = { version = "2", features = ["serde"]}
